sonar.projectKey=notifinance-backend
sonar.projectName=NotiFinance Backend
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=test

sonar.test.inclusions=test/**/*.ts
sonar.exclusions=coverage/**,dist/**,notifinance-frontend/**

sonar.typescript.tsconfigPath=tsconfig.json
sonar.javascript.lcov.reportPaths=coverage/unit/lcov.info,coverage/e2e/lcov.info
