export enum DollarType {
  OFICIAL = 'OFICIAL',
  BLUE = 'BLUE',
  MEP = 'MEP',
  CCL = 'CCL',
  TARJETA = 'TARJETA',
  CRIPTO = 'CRIPTO',
  DOLLAR_MEP_CALC = 'DOLLAR_MEP_CALC',
  DOLLAR_CCL_CALC = 'DOLLAR_CCL_CALC',
}
