import { Alert } from "@/types/alert";

export const mockAlerts: Alert[] = [
  {
    id: "a1",
    userId: "u1",
    assetId: "GGAL",
    alertType: "PRICE",
    condition: "ABOVE",
    threshold: 8000,
    channels: ["IN_APP", "EMAIL"],
    isRecurring: false,
    status: "ACTIVE",
    createdAt: "2023-10-01T10:00:00Z",
  },
  {
    id: "a2",
    userId: "u1",
    assetId: "YPFD",
    alertType: "PCT_CHANGE",
    condition: "PCT_DOWN",
    threshold: 5,
    channels: ["IN_APP"],
    isRecurring: true,
    status: "PAUSED",
    createdAt: "2023-10-05T14:30:00Z",
  },
  {
    id: "a3",
    userId: "u1",
    alertType: "DOLLAR",
    condition: "ABOVE",
    threshold: 1500,
    channels: ["IN_APP", "EMAIL"],
    isRecurring: false,
    status: "TRIGGERED",
    createdAt: "2023-10-10T09:15:00Z",
  },
  {
    id: "a4",
    userId: "u1",
    alertType: "RISK",
    condition: "BELOW",
    threshold: 1000,
    channels: ["IN_APP"],
    isRecurring: true,
    status: "ACTIVE",
    createdAt: "2023-10-12T11:45:00Z",
  },
];
